### ISSUE TITLE
Missing Summary and GaugeHistogram Metric Types

### ISSUE THREAD

**Issue by tommed** [bsm/openmetrics#5]
https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#summary

**Comment by dim** [comment]
Hi Tom, thanks for pointing this out. To give you some background:

1. We decided to omit Summary initially as they are only included in the OpenMetrics spec for backwards compatibly. Instead, Histograms should be used. Nevertheless, I have created a #6 which includes summaries but without quantiles. Please also see [this](https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#client-calculations-and-derived-metrics) for more details.
2. We went back and forth on GaugeHistogram but ultimately decided to omit it. It seems to make very little sense for Go. Are we missing something?

**Comment by tommed** [comment]
Fair enough, happy with that reasoning. 
Thanks and great library!
